openapi: 3.0.0
info:
  title: 1원인증
  version: '1.0'
  description: |
    **서비스 소개**



    **서비스 특징**
  contact:
    email: ask@comtrue.com
    url: 'https://cometrue.ai'
    name: cometrue.ai AI API
  termsOfService: 'https://cometrue.ai/index.php/ai-api-terms-of-service/'
servers:
  - url: 'https://api.cometrue.ai'
paths:
  /api/v1/1won/deposit:
    post:
      summary: 1원인증
      operationId: post-privacy-check
      responses:
        '200':
          description: |-
            OK

            정상응답
          content:
            application/json:
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    status: fail
                    openbanking:
                      rsp_code: A0009
                      rsp_message: API 세부업무 처리실패(리스트 건별 처리결과 확인 요망)
                      bank_rsp_code: '818'
                      bank_rsp_message: 시뮬레이터　응답전문　조회에　실패하였습니다
                properties:
                  status:
                    type: string
                    minLength: 1
                    description: 상태
                    enum:
                      - success
                      - fail
                  auth_code:
                    type: string
                    description: 인증문자열
                    example: 일원인증332
                required:
                  - status
              examples:
                결과:
                  value:
                    status: success
                    auth_code: 일원인증2967
        '400':
          $ref: '#/components/responses/400'
        '401':
          description: |-
            Unauthorized

            허가되지 않은 사용자의 접근
        '409':
          $ref: '#/components/responses/409'
        '500':
          description: |-
            Internal Server Error

            서버가 유지보수 중이거나 응답할 수 없는 상태
      description: "요청계좌에 1원을 송금후 인증문자열을 제공해줍니다.\n\n**기관코드**\n<pre>\n2\tKDB산업은행\t23\tSC제일은행\t37\t전북은행\n3\tIBK기업은행\t27\t한국씨티은행\t39\t경남은행\n4\tKB국민은행\t31\t대구은행\t        81\t하나은행\n7\t수협은행\t        32\t부산은행\t        88\t신한은행\n11\tNH농협은행\t34\t광주은행\t        89\t케이뱅크\n20\t우리은행\t        35\t제주은행\t        90\t카카오뱅크\n</pre>"
      parameters:
        - schema:
            type: string
            example: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Njk3ODI4MzgsImxpY2Vuc2UiOiJiODU1Yzc....
          in: header
          name: Authorization
          description: API Access Token
          required: true
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                organization_code:
                  type: string
                  minLength: 1
                  description: 기관코드
                account:
                  type: string
                  minLength: 1
                  description: 계좌번호
                account_name:
                  type: string
                  minLength: 1
                  description: 예금주 이름
                print_type:
                  type: integer
                  enum:
                    - 0
                    - 1
                    - 2
                    - 3
                    - 4
                    - 5
                    - 6
                  description: |-
                    인증문자열 타입

                    0: 3자리숫자

                    1: 4자리숫자 

                    2: 고정문자열 + 3자리숫자

                    3: 고정문자열 + 4자리숫자

                    4: 3자리숫자 + 고정문자열

                    5: 4자리숫자 + 고정문자열

                    6: 랜덤한 한글 4글자
                prefix:
                  type: string
                  minLength: 1
                  maxLength: 7
                  description: 고정문자열
              required:
                - organization_code
                - account
                - account_name
                - print_type
            examples:
              요청:
                value:
                  organization_code: '89'
                  account: '100000000000'
                  account_name: 아무나
                  print_type: 3
                  prefix: 1원인증
              URL Example:
                value:
                  id_type: jumin
                  image: 'https://www.cometrue.ai/data/license.jpg'
                  is_url: true
        description: 요청헤더의 Content-Type과 body 형식이 일치해야 합니다.
      security: []
    parameters: []
components:
  schemas: {}
  securitySchemes: {}
  responses:
    '400':
      description: |
        Bad Request

        사용자가 키를 잘못 입력하였거나, 값에 문제가 있을때

        <details markdown="1">
        <summary>에러메세지</summary>
        "message": "openbanking timeout"<br>
        "message": "oauth failed"<br>
        "message": "API ERROR"<br>
        "message": "print_type is not correct"<br>
        "message": "exceed request limit"<br>
        "message": "too long prefix"<br>
        </details>
      content:
        application/json:
          schema:
            description: ''
            type: object
            x-examples:
              example-1:
                status: fail
                openbanking:
                  rsp_code: A0009
                  rsp_message: API 세부업무 처리실패(리스트 건별 처리결과 확인 요망)
                  bank_rsp_code: '818'
                  bank_rsp_message: 시뮬레이터　응답전문　조회에　실패하였습니다
            properties:
              status:
                type: string
                minLength: 1
                description: 상태
                enum:
                  - success
                  - fail
              message:
                type: string
                description: API 에러메세지
              openbanking:
                type: object
                description: '오픈뱅킹 에러코드, 메세지'
                properties:
                  rsp_code:
                    type: string
                    minLength: 1
                    description: 오픈뱅킹 응답코드(API)
                  rsp_message:
                    type: string
                    minLength: 1
                    description: 오픈뱅킹 응답메시지(API)
                  bank_rsp_code:
                    type: string
                    minLength: 1
                    description: 응답코드(참가은행)
                  bank_rsp_message:
                    type: string
                    minLength: 1
                    description: 응답메시지(참가은행)
            required:
              - status
              - message
          examples:
            결과:
              value:
                status: fail
                openbanking:
                  rsp_code: A0009
                  rsp_message: API 세부업무 처리실패(리스트 건별 처리결과 확인 요망)
                  bank_rsp_code: '815'
                  bank_rsp_message: '예금주명 불일치 [수취인성명 불일치]'
    '409':
      description: |-
        Conflict

        서버에서의 처리 중 에러

        <details markdown="1">
        <summary>에러메세지</summary>

        </details>
      content:
        application/json:
          schema:
            description: ''
            type: object
            properties:
              message:
                type: string
            required:
              - message
          examples:
            Vertex detection error:
              value:
                message: 'text detection error: 202'
            Text detection error:
              value:
                message: text detection error
            //OCR error:
              value:
                message: text recognition error
            //Matching error:
              value:
                message: matching error
            onnxexception:
              value:
                message: 'Onnx runtime error: 100'
            stdexception:
              value:
                message: 'Std Exception: 101'
            cvexception:
              value:
                message: 'OpenCV error: 100'
            cannot find text:
              value:
                message: 'text detection error: 201'
            cannot find square:
              value:
                message: 'text detection error: 203'
            not enough to be square:
              value:
                message: 'text detection error: 204'
            not enough contour:
              value:
                message: 'text detection error: 207'
            not enough group:
              value:
                message: 'text detection error: 208'
            cannot find object:
              value:
                message: 'object detection error: 209'
            json decode error:
              value:
                message: Json decode error
            not enough similar area:
              value:
                message: 'text detection error: 206'
    '415':
      description: |-
        Unsupported Media Type

        "error": "invalid Content-Type"
      content:
        application/json:
          schema:
            description: ''
            type: object
            properties:
              result:
                type: object
                properties:
                  message:
                    type: string
                    minLength: 1
                required:
                  - message
              error:
                type: string
                minLength: 1
            required:
              - result
              - error
          examples:
            invalid Content-Type:
              value:
                result:
                  message: fail
                error: invalid Content-Type
        application/xml:
          schema:
            type: object
            properties: {}
          examples:
            example-1:
              value: {}
