openapi: 3.0.0
info:
  title: 인증(auth)
  version: '1.0'
  contact:
    email: ask@comtrue.com
    url: 'https://cometrue.ai'
    name: cometrue.ai AI API
  termsOfService: 'https://cometrue.ai/index.php/ai-api-terms-of-service/'
servers:
  - {}
paths:
  /auth/token:
    post:
      operationId: createToken
      summary: API Access Token 발급
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateToken'
            examples:
              request:
                value:
                  username: test
                  password: f95a5317-66a9-4e19-88b8-f99dd5c667ed
      responses:
        '200':
          description: 올바른 요청 처리
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    description: HTTP 상태 코드
                  expire:
                    type: string
                    format: datetime
                    description: 토큰만료일
                  token:
                    type: string
                    format: jwt
                    description: access token
              examples:
                preview:
                  value:
                    code: 200
                    expire: '2050-01-01T00:00:00+09:00'
                    token: header.payload.hash
        '400':
          description: 잘못된 입력 값
          content:
            application/json:
              schema:
                type: object
                properties:
                  reason:
                    type: string
              examples:
                invalid input:
                  value:
                    reason: 에러에 대한 내용
        '401':
          description: 허가 되지 않은 인증 정보
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    description: HTTP 상태 코드
                  message:
                    type: string
              examples:
                unauthorized:
                  value:
                    reason: invalid authentication
        '500':
          description: 서버 측 처리 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  reason:
                    type: string
              examples:
                server error:
                  value:
                    reason: 에러에 대한 내용
    parameters: []
components:
  schemas:
    CreateKey:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      x-examples: {}
    CreateToken:
      type: object
      x-examples:
        example-1:
          key: 4adfe27e-63d3-45b9-8238-62b6ed6fdb5e
          secret: string
      properties:
        username:
          type: string
        password:
          type: string
  securitySchemes:
    Authorization:
      name: API Key(JWT)
      type: apiKey
      in: query
  responses:
    '401':
      description: |
        허가 되지 않은 인증정보

        <details markdown="1">
        <summary>에러메세지</summary>
        "incorrect Username or Password"<br>
        "missing Username or Password"<br>
        </details>
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
              message:
                type: string
