openapi: 3.0.0
info:
  title: 계정 인증
  version: '1.0'
  contact:
    email: ask@comtrue.com
    url: 'https://cometrue.ai'
    name: cometrue.ai AI API
  termsOfService: 'https://cometrue.ai/index.php/ai-api-terms-of-service/'
  description: |
    **서비스 소개**

    컴트루테크놀로지의 API를 사용하기 위한 토큰을 발급하는 API입니다.

    HTTP요청헤더에 발급 받은 토큰을 Authorization 정보에 추가 하여 API를 이용 할 수 있습니다.
servers:
  - url: 'https://api.cometrue.ai'
paths:
  /auth/token:
    post:
      operationId: createToken
      summary: API Access Token 발급
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateToken'
            examples:
              request:
                value:
                  username: test
                  password: f95a5317-66a9-4e19-88b8-f99dd5c667ed
      responses:
        '200':
          description: |-
            OK

            정상응답
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    description: HTTP 상태 코드
                  expire:
                    type: string
                    format: datetime
                    description: 토큰만료일
                  token:
                    type: string
                    format: jwt
                    description: access token
              examples:
                preview:
                  value:
                    code: 200
                    expire: '2050-01-01T00:00:00+09:00'
                    token: header.payload.hash
        '401':
          $ref: '#/components/responses/401'
        '403':
          description: Forbidden
        '500':
          description: 서버 측 처리 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  reason:
                    type: string
              examples:
                server error:
                  value:
                    reason: 에러에 대한 내용
      description: |-
        발급받은 username과 passsword로 요청하면 토큰을 발급 받을 수 있습니다.

        토큰의 형태는 jwt이며, `Authorization: Bearer <token>` 와 같이 요청헤더에 추가하여 API를 이용 할 수 있습니다.

        username과 password 발급을 원하시면 [문의하기](https://cometrue.ai/index.php/ai-api-qna/) 를 통해 문의바랍니다.
    parameters: []
components:
  schemas:
    CreateToken:
      type: object
      properties:
        username:
          type: string
          description: 발급받은 username
        password:
          type: string
          description: 발급받은 password
  securitySchemes: {}
  responses:
    '401':
      description: |
        Unauthorized

        허가되지 않은 사용자의 접근

        잘못 되거나 누락된 username, password

        <details markdown="1">
        <summary>에러메세지</summary>
        "incorrect Username or Password"<br>
        "missing Username or Password"<br>
        </details>
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
              message:
                type: string
