openapi: 3.0.0
info:
  title: license
  version: '1.0'
  contact:
    email: info@cometrue.ai
    url: 'https://cometrue.ai'
servers:
  - url: 'https://api.cometrue.ai/v1'
paths:
  /auth:
    get:
      summary: Authentication Using Api Key
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  message:
                    type: string
                    minLength: 1
                required:
                  - message
              examples:
                Example:
                  value:
                    message: ok
        '400':
          description: Bad Request
      operationId: get-auth
      security:
        - api_key: []
components:
  schemas: {}
  securitySchemes:
    api_key:
      name: api_key
      type: apiKey
      in: query
