openapi: 3.0.0
info:
  title: 신용카드 OCR
  version: '1.0'
  description: 신용카드 이미지 텍스트 검출 API
  contact:
    email: info@cometrue.ai
    url: 'https://cometrue.ai'
    name: 인공지능사업부
  termsOfService: 서비스약관
servers:
  - url: 'https://api.cometrue.ai/ocr/v1'
    description: Cometrue
paths:
  /creditcard:
    post:
      summary: 신용카드 OCR
      operationId: post-idocr
      responses:
        '200':
          description: |-
            OK
            정상응답
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  quadrilateral:
                    type: boolean
                    description: 신분증에 해당하는 사각형이 검출되었는지 확인
                  result:
                    type: object
                    description: ''
                    required:
                      - expired_date
                    properties:
                      number:
                        type: string
                        minLength: 1
                        description: 신용카드 번호
                      expired_date:
                        type: string
                        minLength: 1
                        description: 만료일자
                required:
                  - quadrilateral
                  - result
              examples:
                Example:
                  value:
                    quadrilateral: true
                    result:
                      number: '1111222233334444'
                      expired_date: 01/26
        '400':
          description: |-
            Bad Request
            사용자가 키를 잘못 입력하였거나, 값에 문제가 있을때
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  message:
                    type: string
                    minLength: 1
                required:
                  - message
              examples:
                type not given:
                  value:
                    message: type not provided
                image not given:
                  value:
                    message: image not provided
                base64 decoding of the image failed:
                  value:
                    message: image base64 decode error
                Non-acceptable ID:
                  value:
                    message: Unsupported ID type
                Image not readable:
                  value:
                    message: Image cannot be read
                Query image is too small to process:
                  value:
                    message: Image is too small to process
            application/xml:
              schema:
                type: object
                properties: {}
        '401':
          description: |-
            Unauthorized
            허가되지 않은 사용자의 접근
        '409':
          description: |-
            Conflict
            서버에서의 처리 중 에러
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
              examples:
                Vertex detection error:
                  value:
                    message: vertex detection error
                Text detection error:
                  value:
                    message: text detection error
                OCR error:
                  value:
                    message: text recognition error
                Matching error:
                  value:
                    message: matching error
          headers: {}
        '500':
          description: |-
            Internal Server Error
            서버가 유지보수 중이거나 응답할 수 없는 상태
      description: 신용/체크카드의 이미지에서 텍스트 검출하여 결과를 전달합니다.
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                type:
                  type: integer
                  description: '신용카드 가로형: 0, 신용카드 세로형: 1, 체크카드 가로형: 2, 체크카드 세로형: 3'
                image:
                  type: string
                  minLength: 1
                  description: base64로 인코딩 한 스트링
              required:
                - type
                - image
            examples:
              Example:
                value:
                  type: 0
                  image: iVBORw0KGgoAAAANSUhEUgAACbEAAA2zCAYAAADce6KLAAAA....
        description: ''
      security:
        - Authorization: []
    parameters: []
components:
  schemas: {}
  securitySchemes:
    Authorization:
      name: Authorization
      type: apiKey
      in: header
  responses:
    ErrorResponse:
      description: 신분증 인식 및 OCR에 대한 Error Message
      content:
        application/json:
          schema:
            description: ''
            type: object
            properties:
              message:
                type: string
            required:
              - message
