openapi: 3.0.0
info:
  title: 개인증명서분류(스캔)
  version: '1.0'
  description: |-
    **서비스 소개**

    컴트루테크놀로지의 독자적인 사물인식 신경망과 OCR 신경망을 통해 가족관계증명서, 기본증명서, 주민등록 등·초본 등 개인을 증명하는 문서종류에 대해 분류를 수행합니다.

    스캐너를 통해 스캔된 다량의 개인 증명서 파일에 대해 빠르고 정확한 분류를 수행합니다.

    **서비스 특징**

    *지원가능 문서 21종*
    1. 주민등록증
    2. 운전면허증
    3. 여권
    4. 외국인등록증
    5. 가족관계증명서
    6. 기본증명서
    7. 혼인관계증명서
    8. 입양관계증명서
    9. 친양자입양관계증명서
    10. 주민등록표 초본
    11. 개인인감증명서
    12. 출입국에 관한 사실증명서
    13. 본인서명사실확인서
    14. 건강보험증
    15. 근로소득원천징수영수증
    16. 후견등기사항증명서
    17. 소득확인증명서(개인종합자산관리계좌가입용)
    18. 소득금액증명원
    19. 거주자증명서
    20. 은행통장사본
    21. 기타


    스캔된 파일 데이터에 대해 개인 증명서의 종류에 따라 분류가 가능합니다.<br>
    사물인식 신경망을 활용하여 자동 분류를 수행합니다.<br>
    다량의 개인증명서 데이터에 대해 빠르고 정확한 분류를 수행합니다.<br>
    (*개인증명서 양식 추가는 별도 문의 필요)
  contact:
    email: ask@comtrue.com
    url: 'https://cometrue.ai'
    name: cometrue.ai AI API
  termsOfService: 'https://cometrue.ai/index.php/ai-api-terms-of-service/'
servers:
  - description: Cometrue
paths:
  /document-classification:
    post:
      summary: 개인 증명서 분류(스캔)
      operationId: post-documentclassification
      responses:
        '200':
          description: |-
            OK
            정상응답
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  id:
                    type: string
                    minLength: -1
                    maxLength: 30
                    description: |
                      알 수 없음: -1

                      주민등록증: 0

                      건강보험증: 1

                      근로소득원천징수영수증: 2

                      주민등록표초본: 3

                      거주자증명서: 4

                      출입국에 관한 사실증명서: 5

                      후견등기사항증명서: 6

                      소득확인증명서(개인종합자산관리계좌가입용): 7

                      여권: 8

                      은행통장사본: 9

                      법인인감증명서: 10

                      법인등기부등본: 11


                      외국인등록증: 12

                      운전면허증: 13

                      분류 이외의 문서: 14

                      개인인감증명서&본인서명확인서: 15

                      관계증명서(후견,가족,기본,혼인,입양,친양자): 16

                      사업자등록증&고유번호증: 17

                      사업자등록증명&폐업사실증명&소득금액증명: 18

                      개인인감증명서: 19

                      본인서명확인서: 20

                      기본증명서: 21

                      관계증명서-가족관계증명서: 22

                      관계증명서-혼인관계증명서: 23

                      관계증명서-친양자입양관계증명서: 24

                      관계증명서-입양관계증명서: 25

                      사업자등록증: 26

                      고유번호증: 27

                      사업자등록증명: 28

                      폐업사실증명: 29

                      소득금액증명: 30
              examples:
                사업자등록증:
                  value:
                    id: '26'
        '400':
          description: |-
            Bad Request
            사용자가 키를 잘못 입력하였거나, 값에 문제가 있을때
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  message:
                    type: string
                    minLength: 1
                required:
                  - message
              examples:
                id_type not given:
                  value:
                    message: id_type not provided
                image not given:
                  value:
                    message: image not provided
                base64 decoding of the image failed:
                  value:
                    message: image base64 decode error
                Non-acceptable ID:
                  value:
                    message: Unsupported ID type
                Image not readable:
                  value:
                    message: Image cannot be read
                Query image is too small to process:
                  value:
                    message: Image is too small to process
            application/xml:
              schema:
                type: object
                properties: {}
        '401':
          description: |-
            Unauthorized
            허가되지 않은 사용자의 접근
        '409':
          description: |-
            Conflict
            서버에서의 처리 중 에러
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
              examples:
                Vertex detection error:
                  value:
                    message: vertex detection error
                Text detection error:
                  value:
                    message: text detection error
                OCR error:
                  value:
                    message: text recognition error
                Matching error:
                  value:
                    message: matching error
          headers: {}
        '500':
          description: |-
            Internal Server Error
            서버가 유지보수 중이거나 응답할 수 없는 상태
      description: |-
        가족관계증명서, 기본증명서, 주민등록 등·초본 등 개인을 증명하는 문서종류에 대해 분류를 수행합니다.

        분류결과를 해당 문서의 번호로 제공합니다.
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                image:
                  type: string
                  minLength: 1
                  description: base64로 인코딩 한 스트링 or http URL
                is_url:
                  type: boolean
                  description: image속성이 url일때 true
              required:
                - image
            examples:
              Base64 Example:
                value:
                  image: iVBORw0KGgoAAAANSUhEUgAACbEAAA2zCAYAAADce6KLAAAA....
              URL Example:
                value:
                  id_type: jumin
                  image: 'https://www.cometrue.ai/data/license.jpg'
                  is_url: true
        description: ''
      security:
        - api_key: []
      x-internal: false
    parameters: []
components:
  schemas: {}
  securitySchemes:
    api_key:
      name: api_key
      type: apiKey
      in: query
      description: api.cometrue.ai에서 발급받은 API key
  responses:
    ErrorResponse:
      description: 신분증 인식 및 OCR에 대한 Error Message
      content:
        application/json:
          schema:
            description: ''
            type: object
            properties:
              message:
                type: string
            required:
              - message
