openapi: 3.0.0
info:
  title: Identifcation
  version: '1.0'
  description: 신분증 진위여부에 필요한 정보들을 신분증 이미지에서 검출하여 주는 API입니다.
  contact:
    email: info@cometrue.ai
    url: 'https://cometrue.ai'
    name: 인공지능사업부
  termsOfService: 서비스약관
servers:
  - url: 'https://api.cometrue.ai/v1'
    description: Cometrue
paths:
  /idocr:
    post:
      summary: Identification Card OCR
      operationId: post-idocr
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  quadrilateral:
                    type: boolean
                    description: 신분증에 해당하는 사각형이 검출되었는지 확인
                  result:
                    type: object
                    description: ''
                    required:
                      - name
                      - number
                      - title
                    properties:
                      date:
                        type: string
                        minLength: 1
                        description: 주민등록증 발급일자
                      name:
                        type: string
                        minLength: 1
                        description: 성명
                      number:
                        type: string
                        minLength: 1
                        description: |-
                          주민등록증 - 주민등록번호
                          운전면허증 - 운전면허번호
                      title:
                        type: string
                        minLength: 1
                        description: 신분증 종류
                      birth_dt:
                        type: string
                        description: 운전면허증 생년월일
                      code:
                        type: string
                        description: 운전면허증 식별코드
                required:
                  - quadrilateral
                  - result
              examples:
                주민등록증:
                  value:
                    quadrilateral: true
                    result:
                      date: 2009.8.13.
                      name: 홍길동
                      number: 610220-1250511
                      title: 주민등록증
                운전면허증:
                  value:
                    quadrilateral: true
                    result:
                      birth_dt: '19660220'
                      code: 7wggen
                      name: 홍길동
                      number: 11-90-041222-33
                      title: 자동차운전면허증
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  message:
                    type: string
                    minLength: 1
                required:
                  - message
              examples:
                Example:
                  value:
                    message: Error Message
        '401':
          description: Unauthorized
        '429':
          description: Too Many Requests
        '500':
          description: Internal Server Error
      description: |-
        신분증 인식 후 텍스트 검출하여 돌려줍니다.
        지원하는 신분증은 한국인 주민등록증, 한국인 운전면허증입니다.
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                id_type:
                  type: string
                  minLength: 1
                  description: 'driver, jumin 을 지원함'
                image:
                  type: string
                  minLength: 1
                  description: base64로 인코딩 한 스트링 or http URL
                is_url:
                  type:
                    - string
                    - boolean
                  description: image속성이 url일때 true
              required:
                - id_type
                - image
            examples:
              Base64 Example:
                value:
                  id_type: jumin
                  image: iVBORw0KGgoAAAANSUhEUgAACbEAAA2zCAYAAADce6KLAAAA....
              URL Example:
                value:
                  id_type: jumin
                  image: iVBORw0KGgoAAAANSUhEUgAACbEAAA2zCAYAAADce6KLAAAA....
                  is_url: true
        description: ''
      security:
        - api_key: []
    parameters: []
components:
  schemas: {}
  securitySchemes:
    api_key:
      name: api_key
      type: apiKey
      in: query
      description: api.cometrue.ai에서 발급받은 API key
  responses: {}
