openapi: 3.1.0
info:
  title: 일반 OCR
  version: '1.0'
  description: |-
    **서비스 소개**

    컴트루테크놀로지의 자체개발 OCR 신경망을 통해 책, 문서, 서식, 실환경 이미지에 포함된 문자 영역을 검출하고 OCR을 수행합니다.

    **서비스 특징**

    문자 영역을 자동으로 검출하여 OCR을 진행합니다.<br>
    OCR 수행 후 검색엔진과 연동하거나, 개인정보 검출을 통해 보안 솔루션으로도 활용할 수 있습니다.<br>
    다양한 비정형 문서에 대한 OCR을 수행하여 업무자동화가 가능합니다.<br>
    높은 정확성과 빠른 처리속도로 수행합니다.
  contact:
    email: ask@comtrue.com
    url: 'https://cometrue.ai'
    name: cometrue.ai AI API
  termsOfService: 'https://cometrue.ai/index.php/ai-api-terms-of-service/'
servers:
  - {}
paths:
  /text-ocr:
    post:
      summary: 일반 OCR
      operationId: post-textocr
      responses:
        '200':
          description: |-
            OK

            정상응답
          content:
            application/json:
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    Template: ''
                    ROI:
                      - index: 0
                        x: 63
                        'y': 21
                        width: 175
                        height: 45
                        text: 주민등록증
                        tag: ''
                        language: ''
                        xPoints:
                          - 63
                          - 239
                          - 238
                          - 62
                        yPoints:
                          - 21
                          - 24
                          - 66
                          - 63
                      - index: 1
                        x: 69
                        'y': 82
                        width: 160
                        height: 31
                        text: 정승일(x-)
                        tag: ''
                        language: ''
                        xPoints:
                          - 69
                          - 229
                          - 229
                          - 69
                        yPoints:
                          - 82
                          - 84
                          - 113
                          - 112
                      - index: 2
                        x: 60
                        'y': 118
                        width: 178
                        height: 22
                        text: 690212-1148921
                        tag: ''
                        language: ''
                        xPoints:
                          - 60
                          - 239
                          - 238
                          - 60
                        yPoints:
                          - 118
                          - 120
                          - 140
                          - 138
                      - index: 3
                        x: 51
                        'y': 154
                        width: 228
                        height: 20
                        text: 인천광역시연수구옥련동633
                        tag: ''
                        language: ''
                        xPoints:
                          - 51
                          - 279
                          - 279
                          - 51
                        yPoints:
                          - 154
                          - 155
                          - 174
                          - 173
                      - index: 4
                        x: 52
                        'y': 173
                        width: 188
                        height: 17
                        text: 현대아파트207동1504호
                        tag: ''
                        language: ''
                        xPoints:
                          - 52
                          - 240
                          - 240
                          - 53
                        yPoints:
                          - 173
                          - 172
                          - 190
                          - 191
                      - index: 5
                        x: 129
                        'y': 240
                        width: 196
                        height: 23
                        text: 인천광역시연수구청장
                        tag: ''
                        language: ''
                        xPoints:
                          - 129
                          - 325
                          - 325
                          - 129
                        yPoints:
                          - 240
                          - 240
                          - 263
                          - 263
                properties:
                  ROI:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    description: 텍스트 영역 리스트
                    items:
                      type: object
                      description: 텍스트 영역
                      properties:
                        index:
                          type: number
                          description: 리스트 인덱스
                        x:
                          type: number
                          description: 텍스트 영역의 왼쪽 상단 x 좌표
                        'y':
                          type: number
                          description: 텍스트 영역의 왼쪽 상단 y 좌표
                        width:
                          type: number
                          description: 텍스트 영역 넓이
                        height:
                          type: number
                          description: 텍스트 영역 높이
                        text:
                          type: string
                          description: 검출된 텍스트
                        xPoints:
                          type: array
                          description: '텍스트 영역을 이루는 x 좌표 리스트(왼쪽 상단, 오른쪽 상단, 오른쪽 하단, 왼쪽 하단 순서)'
                          items:
                            type: integer
                        yPoints:
                          type: array
                          description: '텍스트 영역을 이루는 y 좌표 리스트(왼쪽 상단, 오른쪽 상단, 오른쪽 하단, 왼쪽 하단 순서)'
                          items:
                            type: integer
              examples:
                추출결과:
                  value:
                    Template: ''
                    ROI:
                      - index: 0
                        x: 414
                        'y': 302
                        width: 1230
                        height: 192
                        text: 대한민국
                        tag: ''
                        language: ''
                        xPoints:
                          - 414
                          - 1642
                          - 1644
                          - 417
                        yPoints:
                          - 302
                          - 291
                          - 494
                          - 505
                      - index: 1
                        x: 412
                        'y': 521
                        width: 1241
                        height: 134
                        text: republicofkorea
                        tag: ''
                        language: ''
                        xPoints:
                          - 412
                          - 1651
                          - 1653
                          - 414
                        yPoints:
                          - 521
                          - 505
                          - 655
                          - 671
                      - index: 2
                        x: 792
                        'y': 2140
                        width: 547
                        height: 155
                        text: 여권
                        tag: ''
                        language: ''
                        xPoints:
                          - 792
                          - 1335
                          - 1339
                          - 797
                        yPoints:
                          - 2140
                          - 2129
                          - 2295
                          - 2306
                      - index: 3
                        x: 730
                        'y': 2354
                        width: 657
                        height: 113
                        text: passport
                        tag: ''
                        language: ''
                        xPoints:
                          - 730
                          - 1378
                          - 1387
                          - 739
                        yPoints:
                          - 2354
                          - 2321
                          - 2467
                          - 2500
            application/xml:
              schema:
                type: object
                properties: {}
        '400':
          description: |-
            Bad Request

            사용자가 키를 잘못 입력하였거나, 값에 문제가 있을때
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  message:
                    type: string
                    minLength: 1
                required:
                  - message
              examples:
                id_type not given:
                  value:
                    message: id_type not provided
                image not given:
                  value:
                    message: image not provided
                base64 decoding of the image failed:
                  value:
                    message: image base64 decode error
                Non-acceptable ID:
                  value:
                    message: Unsupported ID type
                Image not readable:
                  value:
                    message: Image cannot be read
                Query image is too small to process:
                  value:
                    message: Image is too small to process
            application/xml:
              schema:
                type: object
                properties: {}
        '401':
          description: |-
            Unauthorized

            허가되지 않은 사용자의 접근
        '409':
          description: |-
            Conflict

            서버에서의 처리 중 에러
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
              examples:
                Vertex detection error:
                  value:
                    message: vertex detection error
                Text detection error:
                  value:
                    message: text detection error
                OCR error:
                  value:
                    message: text recognition error
                Matching error:
                  value:
                    message: matching error
          headers: {}
        '500':
          description: |-
            Internal Server Error

            서버가 유지보수 중이거나 응답할 수 없는 상태
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                image:
                  type: string
              required:
                - image
            examples:
              Base64 Example:
                value:
                  image: iVBORw0KGgoAAAANSUhEUgAACbEAAA2zCAYAAADce6KLAAAA....
        description: ''
      description: 문자 영역을 자동으로 검출하여 해당 영역의 정보를 리스트로 제공합니다.
    parameters: []
components:
  schemas: {}
  responses:
    ErrorResponse:
      description: Example response
      content:
        application/json:
          schema:
            properties:
              id:
                type: string
